version: 0.0.{build}

image: Visual Studio 2022

configuration: Release

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: UIAutoVa.sln

after_build:
- 7z a UIAutoVa_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\UIAutoVa\src\bin\%CONFIGURATION%\*.* -r

artifacts:
  - path: UIAutoVa_*.zip
